version: '3.8'

services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp-${DOMAIN}
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      # These variables are for the nginx-proxy
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}
    volumes:
      # Mount the entire WP directory for code, themes, and plugins
      - ./html:/var/www/html
      # Mount our custom PHP config for performance tuning
      - ./conf/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
      # Mount a volume for logs
      - ./logs/php:/var/log/php
    networks:
      - web # Exposed to the public-facing proxy
      - internal # For private communication with the database
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: db-${DOMAIN}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      # Persist database data
      - ./db:/var/lib/mysql
      # Mount a volume for logs
      - ./logs/db:/var/log/mysql
    networks:
      - internal # Only on the private network, not exposed to the proxy

networks:
  web:
    external: true
  internal:
    driver: bridge