version: '3.8'

services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp-${DOMAIN}
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${LE_EMAIL}
    volumes:
      - ./html:/var/www/html
    networks:
      - web
      - internal

  db:
    image: mariadb:10.11
    container_name: db-${DOMAIN}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    driver: bridge
